name: feature branch pipline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev


defaults:
  run:
    shell: bash

jobs:
  merge_request_to_dev_pipline:
    runs-on: ubuntu-latest
#    runs-on :
#      - self-hosted
#      - evstal-local-pc-label
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.12'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: check code format
        run: |
           # Stop the build if there are any issues detected by flake8
           flake8 . --count --show-source --statistics --max-complexity=10 --max-line-length=127

      - name: set up env file for tests
        run: cat env_files/.env.local > .env

      - name: Docker Compose Up
        run: docker-compose up -d

      - name: Run tests
        run: |
          docker exec social_clone_app python manage.py test_db_connection
          docker exec social_clone_app python manage.py test
        
